# Generated by Django 3.2.10 on 2023-05-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230505_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='status_friend',
            field=models.CharField(default=1, max_length=150, verbose_name='Статус друга'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friends',
            name='status_user',
            field=models.CharField(default=2, max_length=150, verbose_name='Статус пользователя'),
            preserve_default=False,
        ),
    ]
