# Generated by Django 3.2.10 on 2023-05-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230505_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='status_friend',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='friends',
            name='status_user',
            field=models.BooleanField(),
        ),
    ]
