# Generated by Django 3.2.10 on 2023-05-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230505_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='status_friend',
            new_name='status_user_from',
        ),
        migrations.RenameField(
            model_name='friends',
            old_name='status_user',
            new_name='status_user_to',
        ),
        migrations.RenameField(
            model_name='friends',
            old_name='users',
            new_name='user_from',
        ),
        migrations.RenameField(
            model_name='friends',
            old_name='friend',
            new_name='user_to',
        ),
    ]
