# Generated by Django 3.2.10 on 2023-05-07 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230505_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
