# Generated by Django 3.2.10 on 2023-05-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_friends_user_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='status_user_from',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='status_user_to',
            field=models.BooleanField(null=True),
        ),
    ]
